---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
  labels:
    app.kubernetes.io/name: weather-backend
    app.kubernetes.io/component: weather-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weather-backend
      app.kubernetes.io/component: weather-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weather-backend
        app.kubernetes.io/component: weather-backend
    spec:
      containers:
        - name: weather-backend
          image: ghcr.io/kammererlara/swm2_2at_kammerer_backend:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: weather-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"