---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/component: {{ .Values.global.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.global.name }}
      app.kubernetes.io/component: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.global.name }}
        app.kubernetes.io/component: {{ .Values.global.name }}
    spec:
      containers:
        - name: {{ .Values.global.name }}
          image: "{{ .Values.global.image }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.global.port }}
              name: http
          envFrom:
            - secretRef:
                name: weather-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"