---
apiVersion: v1
kind: Service
metadata:
  name: weather-backend
  labels:
    app.kubernetes.io/name: weather-backend
    app.kubernetes.io/component: weather-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: weather-backend
    app.kubernetes.io/component: weather-backend