---
apiVersion: v1
kind: Secret
metadata:
  name: weather-secrets
type: Opaque
stringData:
  DB_HOST: "{{ .Values.secret.DB_HOST }}"
  DB_PORT: "{{ .Values.secret.DB_PORT }}"
  DB_NAME: "{{ .Values.secret.DB_NAME }}"
  DB_USERNAME: "{{ .Values.secret.DB_USERNAME }}"
  DB_PASSWORD: "{{ .Values.secret.DB_PASSWORD }}"
  AVWX_TOKEN: "{{ .Values.secret.AVWX_TOKEN }}"